export const CLASS_REGISTER_REQUEST="LOGIN_REGISTER_REQUEST";
export const CLASS_REGISTER_SUCCESS="LOGIN_REGISTER_SUCCESS";
export const CLASS_REGISTER_FAILURE="LOGIN_REGISTER_FAIL";



export const Get_CLASSInfo_REQUEST="Get_CLASSInfo_REQUEST";
export const Get_CLASSInfo_SUCCESS="Get_CLASSInfo_SUCCESS";
export const Get_CLASSInfo_FAIL="Get_CLASSInfo_FAIL";


export const Get_AdminOWNPROFILE_REQUEST="Get_CLASSInfo_REQUEST";
export const Get_AdminOWNPROFILE_SUCCESS="Get_CLASSInfo_SUCCESS";
export const Get_AdminOWNPROFILE_FAIL="Get_CLASSInfo_FAIL";

export const Add_Admin_Request="Add_Admin_Request";
export const Add_Admin_Success="Add_Admin_Success";
export const Add_Admin_Fail="Add_Admin_Fail";

export const DELETE_CLASS_REQUEST="DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS="DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL="DELETE_CLASS_FAIL";


export const UPDATE_CLASS_REQUEST="UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS="UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAIL="UPDATE_CLASS_FAIL";


export const REGISTER_COURSE_REQUEST="REGISTER_COURSE_REQUEST";
export const REGISTER_COURSE_SUCCESS="REGISTER_COURSE_SUCCESS";
export const REGISTER_COURSE_FAIL="REGISTER_COURSE_FAIL";


export const ADD_STUDENT_REQUEST="ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS="ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL="ADD_STUDENT_FAIL";

export const GET_ADMINS_REQUEST = "GET_ADMINS_REQUEST";
export const GET_ADMINS_SUCCESS = "GET_ADMINS_SUCCESS";
export const GET_ADMINS_FAIL = "GET_ADMINS_FAIL";
