export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAIL";

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"; 
export const LOGOUT_FAILURE="LOGOUT_FAILURE";

